#!/bin/zsh
#
# ci_post_clone.sh
# Xcode Cloud runs this automatically right after cloning the repo, before
# any build/archive action. Xcode Cloud's fresh clone has none of the
# generated artifacts a local dev machine already has on disk:
#   - node_modules/            (npm install)
#   - dist/                    (npm run build, i.e. `vite build`)
#   - ios/App/App/public/      (npx cap sync -- copies dist/ in)
#   - ios/App/App/capacitor.config.json  (also generated by cap sync)
#   - ios/App/Pods/            (cap sync ios / pod install)
# Without all of the above, the Xcode build fails at the configuration/
# resource-resolution stage before any real compilation, e.g.:
#   "Unable to open base configuration reference file
#    .../Pods-App.release.xcconfig"                        (build 6)
#   "The file 'public' couldn't be opened because there is no such file"
#   "The file 'capacitor.config.json' couldn't be opened..." (build 9)
set -e
set -x

echo "==> ci_post_clone: installing CocoaPods (if needed)"
if ! command -v pod >/dev/null 2>&1; then
  brew install cocoapods
fi

echo "==> ci_post_clone: installing Node.js (if needed)"
if ! command -v node >/dev/null 2>&1; then
  brew install node
fi

cd "$CI_PRIMARY_REPOSITORY_PATH"

echo "==> ci_post_clone: npm install at repo root"
npm install

echo "==> ci_post_clone: build the web app (vite build -> dist/)"
npm run build

echo "==> ci_post_clone: npx cap sync ios (copies dist/ into ios/App/App/public,"
echo "    generates ios/App/App/capacitor.config.json, and runs pod install)"
npx cap sync ios

echo "==> ci_post_clone: done"
