#!/bin/zsh
#
# ci_post_clone.sh
# Xcode Cloud runs this automatically right after cloning the repo, before
# any build/archive action. Xcode Cloud's macOS images do NOT include our
# npm dependencies (node_modules is gitignored) and do not always have
# CocoaPods pre-installed, both of which "pod install" needs -- without
# this script, Xcode Cloud tries to open Pods-App.release.xcconfig, which
# only gets generated by "pod install", and the build fails with
# "Unable to open base configuration reference file".
set -e
set -x

echo "==> ci_post_clone: installing CocoaPods (if needed)"
if ! command -v pod >/dev/null 2>&1; then
  brew install cocoapods
fi

echo "==> ci_post_clone: installing Node.js (if needed)"
if ! command -v node >/dev/null 2>&1; then
  brew install node
fi

echo "==> ci_post_clone: npm install at repo root"
cd "$CI_PRIMARY_REPOSITORY_PATH"
npm install

echo "==> ci_post_clone: pod install"
cd "$CI_PRIMARY_REPOSITORY_PATH/ios/App"
pod install

echo "==> ci_post_clone: done"
